#!/usr/bin/env python3
"""
Regenerate vcdecomp/core/disasm/runtime_opcode_table.py
from docs/runtime_opcode_map_with_snippets.json.

Usage:
    python tools/update_runtime_opcode_table.py
"""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "runtime_opcode_map_with_snippets.json"
TARGET = ROOT / "vcdecomp" / "core" / "disasm" / "runtime_opcode_table.py"


def load_mapping() -> dict[int, str]:
    data = json.loads(DOC.read_text(encoding="utf-8"))
    mapping: dict[int, str] = {}
    for opcode_str, entry in data.items():
        opcode = int(opcode_str)
        mnemonic = entry.get("mnemonic")
        if not mnemonic:
            raise RuntimeError(f"Entry {opcode} is missing 'mnemonic'")
        mapping[opcode] = mnemonic
    if len(mapping) != 150:
        raise RuntimeError(f"Expected 150 opcodes, found {len(mapping)}")
    return dict(sorted(mapping.items()))


def format_table(mapping: dict[int, str]) -> str:
    header = dedent(
        """\
        # Auto-generated by tools/update_runtime_opcode_table.py
        RUNTIME_OPCODE_MAP = {
        """
    )
    body_lines = [f"    {opcode}: \"{mnemonic}\"," for opcode, mnemonic in mapping.items()]
    footer = "}\n"
    return header + "\n".join(body_lines) + "\n" + footer


def main() -> None:
    mapping = load_mapping()
    text = format_table(mapping)
    TARGET.write_text(text, encoding="utf-8")
    print(f"Wrote {TARGET} ({len(mapping)} entries).")


if __name__ == "__main__":
    main()
